---
- name: Configurar LVM no servidor arq
  hosts: arq
  become: yes
  tasks:

    - name: Verificar se o Volume Group 'dados' já existe
      command: vgdisplay dados
      register: vg_check
      ignore_errors: true

    - name: Criar partições físicas (PV) nos discos (com força)
      command: pvcreate -ff -y {{ item }}
      loop:
        - /dev/sdb
        - /dev/sdc
        - /dev/sdd
      when: vg_check.rc != 0

    - name: Criar Volume Group 'dados'
      command: vgcreate dados /dev/sdb /dev/sdc /dev/sdd
      when: vg_check.rc != 0

    - name: Criar Logical Volume 'ifpb' com 15G
      command: lvcreate -n ifpb -L 15G dados
      when: vg_check.rc != 0

    - name: Formatar o LV com ext4
      filesystem:
        fstype: ext4
        dev: /dev/dados/ifpb
      when: vg_check.rc != 0

    - name: Criar ponto de montagem /dados
      file:
        path: /dados
        state: directory

    - name: Adicionar entrada no fstab
      mount:
        path: /dados
        src: /dev/dados/ifpb
        fstype: ext4
        opts: defaults
        state: mounted

