---
# ansible/playbooks/site.yml

- import_playbook: common/base.yml
- import_playbook: common/ntp.yml
- import_playbook: common/ssh.yml

- import_playbook: arq/lvm.yml
- import_playbook: arq/nfs-server.yml

- import_playbook: db/mariadb.yml
- import_playbook: db/autofs.yml

- import_playbook: app/apache.yml
- import_playbook: app/autofs.yml

- import_playbook: cli/firefox.yml
- import_playbook: cli/autofs.yml

