---
# Playbook mestre para orquestração do projeto DevOps

- name: Configuração base de todos os hosts
  import_playbook: common/base.yml

- name: Configuração NTP para todos os hosts
  import_playbook: common/ntp.yml

- name: Configuração do SSH para todos os hosts
  import_playbook: common/ssh.yml

- name: Configuração do LVM no servidor de arquivos (arq)
  import_playbook: arq/lvm.yml

- name: Configuração do servidor NFS no arq
  import_playbook: arq/nfs-server.yml

- name: Configuração do autofs no servidor de banco de dados (db)
  import_playbook: db/autofs.yml

- name: Instalação e configuração do Apache no servidor de aplicação (app)
  import_playbook: app/apache.yml

- name: Configuração do autofs no app
  import_playbook: app/autofs.yml

- name: Instalação do Firefox e X11 no cliente (cli)
  import_playbook: cli/firefox.yml

- name: Configuração do autofs no cli
  import_playbook: cli/autofs.yml
